name: Run SCA tests
description: 'Runs all SCA tests: lint, format and security.'

inputs:
  python_version:
    description: A version of Python to install
    type: string
    required: true

runs:
  using: composite
  steps:
    - name: install Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python_version }}

    - name: install Poetry
      uses: Gr1N/setup-poetry@v8

    - name: create Poetry venv
      shell: bash
      run: |
        poetry env use ${{ inputs.python_version }}
        poetry install

    - name: run flake
      shell: bash
      run: poetry run make lint

    - name: run black
      shell: bash
      run: poetry run make format_check

    - name: run bandit
      shell: bash
      run: poetry run make security