name: Run Docs tests
description: 'Check if documentation is up to date.'

inputs:
  python_version:
    description: A version of Python to install
    type: string
    required: true

runs:
  using: composite
  steps:
    - name: install Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python_version }}
        cache: pip

    - name: install Poetry
      uses: Gr1N/setup-poetry@v8

    - name: create Poetry venv
      shell: bash
      run: |
        poetry env use ${{ inputs.python_version }}
        poetry install

    - name: generate API docs
      shell: bash
      run: poetry run make documentation

    - name: check if documentation needs updating
      shell: bash
      run: |
        if [ "$(git status --porcelain)" ]; then 
          git status
          exit 1
        else
          exit 0
        fi
