name: PanDev PR
description: 'Creates a PR in PanDev repository, a preview (PR) or a mergable (release) one.'

inputs:
  token:
    description: Token to authenticate to PanDev repository
    type: string
    required: true
  ref_name:
    description: A branch name or a release tag
    type: string
    required: true
  pr_no:
    description: PR number, triggers creation of a preview PR
    required: false

runs:
  using: composite
  steps:
    - name: checkout pan.dev
      uses: actions/checkout@v4
      with:
        repository: PaloAltoNetworks/pan.dev
        token: ${{ inputs.token }}
        path: pandev

    - name: download documentation artifact
      uses: actions/download-artifact@v3
      with:
        name: documentation
        path: ./pandev/products/panos/docs

    - name: unpack the documentation
      working-directory: ./pandev/products/panos/docs
      shell: bash
      run: |
        rm -rf 'panos-upgrade-assurance'
        tar xvf documentation.tar
        rm -f documentation.tar

    - name: create a release PR to upstream pan.dev
      if: inputs.pr_no == ''
      uses: peter-evans/create-pull-request@v5
      with:
        path: ./pandev
        token: ${{ inputs.token }}
        delete-branch: true
        branch: "pua_release_${{ inputs.ref_name }}"
        title: "[PAN-OS Upgrade Assurance] documentation update for release: ${{ inputs.ref_name }}"
        commit-message: "docs: PanOS Upgrade Assurance documentation update"
        labels: netsec
        body: |
          # Description
          
          A PR made for changes introduced into documentation on ${{ inputs.ref_name }} release.

          # Types of changes

          New feature (non-breaking change which adds functionality)

    - name: create a preview PR to pan.dev
      id: preview
      if: inputs.pr_no != ''
      uses: peter-evans/create-pull-request@v5
      with:
        path: ./pandev
        token: ${{ inputs.token }}
        delete-branch: true
        branch: "pua_prev_${{ inputs.ref_name }}"
        title: "[PAN-OS Upgrade Assurance][${{ inputs.ref_name }}] documentation PREVIEW - do NOT MERGE"
        commit-message: "docs: PanOS Upgrade Assurance documentation update"
        labels: netsec, DO NOT MERGE
        body: |
          # Description
          
          DO NOT MERGE - preview PR made for changes on branch: ${{ inputs.ref_name }}.

          # Types of changes

          New feature (non-breaking change which adds functionality)

    - name: find if we have a comment
      id: find
      if: steps.preview.outputs.pull-request-url != ''
      uses: peter-evans/find-comment@v2
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body-includes: A Preview PR in PanDev repo has been created
        repository: ${{ github.repository }}

    - name: comment back on the original PR
      if: steps.find.outputs.comment-id == ''
      uses: peter-evans/create-or-update-comment@v3
      with:
        issue-number: ${{ github.event.pull_request.number }}
        repository: ${{ github.repository }}
        body: |
          A Preview PR in PanDev repo has been created. You can view it [here](${{ steps.pr.outputs.pull-request-url }}).
