name: (sub) Build Docker image

defaults:
  run:
    shell: bash

on:
  workflow_call:
    inputs:
      publish:
        description: A flag that triggers publishing to GHCR
        type: boolean
        default: false
      python_version:
        description: A version of Python to install
        type: string
        required: true
      tag_name:
        description: A tag to checkout
        type: string

jobs:

  build:
    name: Build ${{ inputs.publish && 'and publish' || '' }} a Docker image
    runs-on: ubuntu-latest
    # packages write should be needed for publish only - set permissions accordingly from calling workflow
    # permissions:
    #   packages: write
    #   contents: read
    steps:
      - name: checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          ref: ${{ inputs.tag_name }}

      - name: install Python
        uses: actions/setup-python@b64ffcaf5b410884ad320a9cfac8866006a109aa # v4
        with:
          python-version: ${{ inputs.python_version }}

      - name: install Poetry
        uses: Gr1N/setup-poetry@15821dc8a61bc630db542ae4baf6a7c19a994844 # v8
        with:
          poetry-version: "1.8.5"

      - name: get the tag name for new image
        id: tag
        run: |
          echo "version_tag=$(poetry version -s)" >> $GITHUB_OUTPUT

      - name: build and prepare package for containerization
        env:
          PYTHON_VERSION: '${{ inputs.python_version }}'
        run: |
          poetry env use $PYTHON_VERSION
          poetry lock
          poetry build
          poetry export --without-hashes --format=requirements.txt > requirements.txt

      - name: determine docker tags and labels
        id: meta
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5
        with:
          images: ghcr.io/paloaltonetworks/panos_upgrade_assurance
          tags: |
            type=raw,value=latest
            type=semver,pattern=v{{version}},value=${{ steps.tag.outputs.version_tag }}
            type=semver,pattern=v{{major}}.{{minor}},value=${{ steps.tag.outputs.version_tag }}
            type=semver,pattern=v{{major}},value=${{ steps.tag.outputs.version_tag }}

      - name: login to GHCR
        if: inputs.publish
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build ${{ inputs.publish && 'and publish' || '' }}
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5
        with:
          context: .
          push: ${{ inputs.publish }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
