name: Close PR
run-name: "Close Related PAN.DEV PR - (#${{ github.event.number }}) ${{ github.event.pull_request.title }}"

defaults:
  run:
    shell: bash

permissions:
  contents: read

on:
  pull_request:
    branches: ['main']
    types: ['closed']

jobs:
  store_pr_details:
    name: Upload PR details to artifact for closing
    runs-on: ubuntu-latest
    steps:
      - name: save PR details
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }} > ./pr/NR
          echo ${{ github.event.pull_request.head.ref }} > ./pr/HEAD_REF
      - uses: actions/upload-artifact@v4
        with:
          name: pr
          path: pr/
