name: Close PR
run-name: "Close Related PAN.DEV PR - (#${{ github.event.number }}) ${{ github.event.pull_request.title }}"

defaults:
  run:
    shell: bash

permissions:
  contents: read

on:
  pull_request:
    branches: ['main']
    types: ['closed']

jobs:
  store_pr_details:
    name: Upload PR details to artifact for closing
    runs-on: ubuntu-latest
    steps:
      - name: save PR details
        env:
          EVENT_NUMBER: '${{ github.event.number }}'
          PR_REF: '${{ github.event.pull_request.head.ref }}'
        run: |
          mkdir -p ./pr
          echo $EVENT_NUMBER > ./pr/NR
          echo $PR_REF > ./pr/HEAD_REF
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: pr
          path: pr/
