name: (sub) Build Docker image

defaults:
  run:
    shell: bash

on:
  workflow_call:
    inputs:
      publish:
        description: A flag that triggers publishing to GHCR
        type: boolean
        required: false
      poetry_version:
        description: A version of poetry to install
        type: string
        required: true

jobs:

  build:
    name: Build ${{ inputs.publish == 'true' && 'and publish' || '' }} a Docker image
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: install Poetry
        uses: Gr1N/setup-poetry@v8
        with: 
          poetry-version: ${{ inputs.poetry_version }}

      - name: get the tag name for new image
        id: tag
        run: |
          echo "version_tag=paloaltonetworks/panos_upgrade_assurance:$(poetry version -s)" >> $GITHUB_OUTPUT

      - name: build and prepare package for contenarization
        run: |
          poetry lock
          poetry build
          poetry export --without-hashes --format=requirements.txt > requirements.txt

          cat requirements.txt

      - name: login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build ${{ inputs.publish == 'true' && 'and publish' || '' }}
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ inputs.publish }}
          tags: ${{ steps.tag.outputs.version_tag}},paloaltonetworks/panos_upgrade_assurance:latest
