name: PR
run-name: "PR - (#${{ github.event.number }}) ${{ github.event.pull_request.title }}"

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review
    branches: main

permissions:
  contents: read

jobs:

  pyversion:
    name: Discover minimum Python version
    uses: ./.github/workflows/_discover_python_ver.yml

  code_format:
    name: Formatting and security
    needs: pyversion
    uses: ./.github/workflows/sub_format.yml
    with:
      python_version: ${{ needs.pyversion.outputs.pyversion }}

  unit_tests:
    name: Unit Tests
    needs: pyversion
    permissions:
      contents: write
    uses: ./.github/workflows/sub_unittest.yml
    with:
      python_version: ${{ needs.pyversion.outputs.pyversion }}

  documentation_check:
    name: API documentation
    needs: pyversion
    uses: ./.github/workflows/sub_docs.yml
    with:
      python_version: ${{ needs.pyversion.outputs.pyversion }}

  docker_image_test_build:
    name: Build Docker image
    needs: pyversion
    uses: ./.github/workflows/_docker.yml
    permissions:
      contents: read
      packages: read            # since publish is false, read access is ok
    with:
      publish: false
      python_version: ${{ needs.pyversion.outputs.pyversion }}

  store_documentation:
    name: Fetch the updated documentation
    needs:
      - code_format
      - unit_tests
      - documentation_check
      - docker_image_test_build
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: pack the documentation
        working-directory: docs
        run: tar --exclude .DS_Store --exclude sidebars.js -cvf documentation.tar *
      - name: upload the documentation artifact
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: docs/documentation.tar

  store_pr_details:
    name: Upload PR details to artifact
    runs-on: ubuntu-latest
    steps:
      - name: save PR details
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }} > ./pr/NR
          echo ${{ github.event.pull_request.head.ref }} > ./pr/HEAD_REF
      - uses: actions/upload-artifact@v4
        with:
          name: pr
          path: pr/
