name: PR
run-name: "PR - (#${{ github.event.number }}) ${{ github.event.pull_request.title }}"

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review
    branches: ['main']

jobs:

  pyversion:
    name: Discover minimum Python version
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: discover Python version
        id: pyversion
        uses: ./.github/actions/discover_python_version
      - name: display version
        run: echo Python version ${{ steps.pyversion.outputs.pyversion }}

  # code_format:
  #   name: Validate code formatting
  #   needs: [pyversion]
  #   uses: ./.github/workflows/sub_format.yml
  #   with:
  #     python_version: 3.8.1
  #     poetry_version: 1.4.2