name: Post PR Workflow Run

# read-write repo token
# access to secrets
on:
  workflow_run:
    workflows: ["PR"]
    types:
      - completed

permissions:
  contents: write
  pull-requests: write

jobs:

  pr_status:
    name: Get PR details and coverage results from artifacts
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'

    outputs:
      pr_number: ${{ steps.read.outputs.pr_number }}
      pr_head_ref: ${{ steps.read.outputs.pr_head_ref }}

    steps:
      - name: download PR artifact
        uses: actions/download-artifact@v3
        with:
          name: pr
          path: pr

      - name: read PR details from artifact
        id: read
        working-directory: pr
        run: |
          unzip pr.zip
          echo "pr_number=$(cat NR)" >> "$GITHUB_OUTPUT"
          echo "pr_head_ref=$(cat HEAD_REF)" >> "$GITHUB_OUTPUT"

  update_coverage:
    name: Update coverage report on PR
    needs: pr_status
    runs-on: ubuntu-latest
    steps:
      - name: 'Comment on PR'
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            var fs = require('fs');
            var issue_number = Number(fs.readFileSync('./pr/NR'));
            await github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: 'Everything is OK. Thank you for the PR!'
            });

      # # requires pull-requests: write permissions when triggered from PRs
      # - name: Get coverage
      #   uses: orgoro/coverage@v3.1
      #   with:
      #       coverageFile: pr/coverage.xml
      #       token: ${{ secrets.GITHUB_TOKEN }}
      #       thresholdAll: 0.95
      #       thresholdNew: 0.90
      #       thresholdModified: 0.95



  pandev_pr:
    name: Create a preview PR for pan.dev
    needs: pr_status
    runs-on: ubuntu-latest
    steps:
      - name: checkout pan.dev
        uses: actions/checkout@v4
        with:
          repository: PaloAltoNetworks/pan.dev
          token: ${{ secrets.CLSC_PAT }}

      - name: download documentation artifact
        uses: actions/download-artifact@v3
        with:
          name: documentation
          path: products/panos/docs

      - name: unpack the documentation
        working-directory: products/panos/docs
        run: |
          rm -rf 'panos-upgrade-assurance'
          tar xvf documentation.tar
          rm -f documentation.tar

      - name: create a PR to upstream pan.dev
        id: pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.CLSC_PAT }}
          delete-branch: true
          branch: "pua_prev_${{ needs.pr_status.outputs.pr_head_ref }}"
          title: "[PAN-OS Upgrade Assurance][${{ needs.pr_status.outputs.pr_head_ref }}] documentation PREVIEW - do NOT MERGE"
          commit-message: "docs: PanOS Upgrade Assurance documentation update"
          labels: netsec, DO NOT MERGE
          body: |
            # Description
            
            DO NOT MERGE - preview PR made for changes on branch: ${{ needs.pr_status.outputs.pr_head_ref }}.

            # Types of changes

            New feature (non-breaking change which adds functionality)

      - name: find if we have a comment
        uses: peter-evans/find-comment@v2
        id: find
        with:
          issue-number: ${{ needs.pr_status.outputs.pr_number }}
          body-includes: A Preview PR in PanDev repo has been created
          repository: ${{ github.repository }}

      - name: comment back on the original PR
        if: steps.find.outputs.comment-id == '' &&  steps.pr.outputs.pull-request-url != ''
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ needs.pr_status.outputs.pr_number }}
          repository: ${{ github.repository }}
          body: |
            A Preview PR in PanDev repo has been created. You can view it [here](${{ steps.pr.outputs.pull-request-url }}).


