name: (publish) Python package
run-name: Publish a Python package for release ${{ github.event.release.tag_name }}

on:
  release:
    types: released

permissions:
  contents: read

jobs:
  pyversion:
    name: Discover minimum Python version
    uses: ./.github/workflows/_discover_python_ver.yml

  package:
    name: Publish Python package
    runs-on: ubuntu-latest
    needs: pyversion
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install Python
        uses: actions/setup-python@b64ffcaf5b410884ad320a9cfac8866006a109aa # v4
        with:
          python-version: ${{ needs.pyversion.outputs.pyversion }}

      - name: Install Poetry
        uses: Gr1N/setup-poetry@15821dc8a61bc630db542ae4baf6a7c19a994844 # v8
        with:
          poetry-version: "1.8.5"

      - name: Create Poetry venv 
        run: |
          poetry env use ${{ needs.pyversion.outputs.pyversion }}
      
      - name: Publish to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry publish --build --skip-existing