name: (publish) Docker image
run-name: Publish a Docker image for release ${{ github.event.release.tag_name }}

permissions:
  contents: read

on:
  release:
    types: released

jobs:
  pyversion:
    name: Discover minimum Python version
    runs-on: ubuntu-latest
    outputs:
      pyversion: ${{ steps.pyversion.outputs.pyversion }}
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: discover Python version
        id: pyversion
        uses: ./.github/actions/discover_python_version

  docker_image_test_build:
    name: Build Docker image
    needs: pyversion
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}
      - name: build docker image
        uses: ./.github/actions/build_image
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          python_version: ${{ needs.pyversion.outputs.pyversion }}
          publish: true
