name: (publish) Docker image
run-name: Publish a Docker image for release ${{ github.event.release.tag_name }}

permissions:
  contents: read

on:
  release:
    types: released

jobs:
  pyversion:
    name: Discover minimum Python version
    runs-on: ubuntu-latest
    outputs:
      pyversion: ${{ steps.pyversion.outputs.pyversion }}
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: discover Python version
        id: pyversion
        uses: ./.github/actions/discover_python_version

  docker_image_build:
    name: Build and Publish Docker image
    needs: pyversion
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/_docker.yml
    with:
      publish: true
      python_version: ${{ needs.pyversion.outputs.pyversion }}
      tag_name: ${{ github.event.release.tag_name }}
