name: (publish) Python package
run-name: Publish a Python package for release ${{ github.event.release.tag_name }}

on:
  release:
    types: released

permissions:
  contents: read

jobs:

  package:
    name: Publish Python package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: discover Python version
        id: pyversion
        uses: ./.github/actions/discover_python_version

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ steps.pyversion.outputs.pyversion }}
          cache: pip

      - name: Install Poetry
        uses: Gr1N/setup-poetry@v8

      - name: Create Poetry venv 
        run: |
          poetry env use ${{ steps.pyversion.outputs.pyversion }}
      
      - name: Publish to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry publish --build --skip-existing