name: Release
run-name: "Continous Release"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * 3' # this means every Wednesday @1am UTC

permissions:
  contents: read

jobs:

  rc:
    name: Check if we need a new release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: read
    outputs:
      rc: ${{ steps.rc.outputs.new_release_published }}
      ver: ${{ steps.rc.outputs.new_release_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if new version will be produced
        id: rc
        uses: cycjimmy/semantic-release-action@v3
        with:
          dry_run: true
          semantic_version: 19.0
          extra_plugins: |
            conventional-changelog-conventionalcommits@^5.0.0
            @semantic-release/git@^10.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  pyversion:
    name: Discover minimum Python version
    needs: [rc]
    if: needs.rc.outputs.rc == 'true'
    runs-on: ubuntu-latest
    outputs:
      pyversion: ${{ steps.pyversion.outputs.pyversion }}
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: discover Python version
        id: pyversion
        uses: ./.github/actions/discover_python_version

  code_format:
    name: Validate code formatting
    needs: [pyversion]
    uses: ./.github/workflows/sub_format.yml
    with:
      python_version: ${{ needs.pyversion.outputs.pyversion }}
      poetry_version: 1.4.2

  documentation_check:
    name: Validate that the API documentation is up to date
    needs: [pyversion]
    uses: ./.github/workflows/sub_docs.yml
    with:
      python_version: ${{ needs.pyversion.outputs.pyversion }}
      poetry_version: 1.4.2

  release:
    name: Create a new release
    runs-on: ubuntu-latest
    if: needs.rc.outputs.rc == 'true'
    needs:
      - rc
      - code_format
      - documentation_check
    concurrency: release
    permissions:
      contents: write
      issues: read
    outputs:
      released: ${{ steps.release.outputs.new_release_published }}
      tag: ${{ steps.release.outputs.new_release_git_tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Poetry
        uses: Gr1N/setup-poetry@v8
        with: 
          poetry-version: 1.4.2

      - name: Create Poetry venv
        run: poetry install

      - name: Build and publish to PyPI
        env:
          VERSION: ${{ needs.rc.outputs.ver }}
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry version "${VERSION}"
          poetry publish --build

      - name: Create release and publish to GitHub
        id: release
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: 19.0
          extra_plugins: |
            conventional-changelog-conventionalcommits@^5.0.0
            @semantic-release/git@^10.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  cleanup_pandev:
    name: Cleanup documentation release PRs @PAN.DEV
    runs-on: ubuntu-latest
    if: needs.release.outputs.release == 'true'
    needs: release
    permissions:
      pull_request: write
    steps:
      - name: cleanup old PRs
        uses: actions/github-script@v6
        with:
          result-encoding: string
          github-token: ${{ secrets.CLSC_PAT }}
          script: |
            let prs = await github.rest.pulls.list({
              owner: "PaloAltoNetworks",
              repo: "pan.dev",
              state: "open",
            })

            let prs_list = prs.data
            console.log("Total PRs found: " + prs_list.length)

            let found = false
            let pr_no

            if (prs_list.length > 0){
              console.log("Removing obsolete PRs:")
              for (let pr of prs_list){
                if (pr.head.label.includes("PaloAltoNetworks:v")){
                  console.log(" - removing PR (#" + pr.number + ") " + pr.title + " -> " + pr.url)

                  await github.rest.pulls.update({
                    owner: "PaloAltoNetworks",
                    repo: "pan.dev",
                    pull_number: pr.number,
                    state: "closed",
                  })
                }
              }
            }

  update_pandev:
    name: Create a PR for pan.dev
    if: needs.release.outputs.release == 'true'
    needs: 
      - cleanup_pandev
      - release
    uses: ./.github/workflows/sub_pandev.yml
    secrets: inherit
    with:
      head_branch: ${{ needs.release.outputs.tag }}
      preview: false
