name: (sub) Documentation check

defaults:
  run:
    shell: bash

on:
  workflow_call:
    inputs:
      python_version:
        description: A version of Python to install
        type: string
        required: true
      poetry_version:
        description: A version of poetry to install
        type: string
        required: true

jobs:

  documentation:
    name: Verify if generated API documentation is up to date
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python_version }}

      - name: Install Poetry
        uses: Gr1N/setup-poetry@v8
        with: 
          poetry-version: ${{ inputs.poetry_version }}

      - name: Create Poetry venv
        run: poetry install

      - name: Generate API docs
        run: poetry run make documentation

      - name: Check if documentation needs updating
        run: |
          if [ "$(git status --porcelain)" ]; then 
            git status
            exit 1
          else
            exit 0
          fi
