name: (sub) Code Format and Security

defaults:
  run:
    shell: bash

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      head_branch:
        description: Name of a branch from which the PR in source repository is created
        type: string
        required: true

jobs:
  fetch:
    name: Fetch the updated documentation
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: pack the documentation
        working-directory: docs
        run: tar --exclude .DS_Store --exclude sidebars.js -cvf documentation.tar *
      - name: upload the documentation artifact
        uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: docs/documentation.tar

  update:
    name: Prepare a PR for pan.dev
    needs: [fetch]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: checkout pan.dev fork
        uses: actions/checkout@v3
        with:
          repository: PaloAltoNetworks/pan.dev
          token: ${{ secrets.CLSC_PAT }}
          # fetch: 0
      - name: download documentation artifact
        uses: actions/download-artifact@v3
        with:
          name: documentation
          path: products/panos/docs
      - name: unpack the documentation
        working-directory: products/panos/docs
        run: |
          rm -rf 'panos-upgrade-assurance'
          tar xvf documentation.tar
          rm -f documentation.tar
      - name: create a PR to upstream pan.dev
        uses: peter-evans/create-pull-request@head-repo
        with:
          push-to-fork: PaloAltoNetworks/panos-upgrade-assurance-pan.dev
          token: ${{ secrets.CLSC_PAT }}
          delete-branch: true
          branch: "${{ inputs.head_branch }}"
          title: "[PAN-OS Upgrade Assurance][${{ inputs.head_branch }}] documentation PREVIEW - do NOT MERGE"
          commit-message: "docs: documentation update"
          body: |
            # Description
            
            DO NOT MERGE - preview PR made for changes on branch: ${{ inputs.head_branch }}.

            # Types of changes

            New feature (non-breaking change which adds functionality)
