name: (sub) Unit Tests

defaults:
  run:
    shell: bash

on:
  workflow_call:
    inputs:
      python_version:
        description: A version of Python to install
        type: string
        required: true


permissions:
  # Gives the action the necessary permissions for pushing data to the
  # python-coverage-comment-action branch, and for editing existing
  # comments (to avoid publishing multiple comments in the same PR)
  contents: write

jobs:

  unittests:
    name: Verify unit tests are successful
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install Python
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4
        with:
          python-version: ${{ inputs.python_version }}

      - name: Install Poetry
        uses: Gr1N/setup-poetry@15821dc8a61bc630db542ae4baf6a7c19a994844 # v8

      - name: Create Poetry venv
        run: |
          poetry env use ${{ inputs.python_version }}
          poetry install

      - name: Run unit tests and coverage
        run: poetry run make test_coverage

      # coverage results comment is uploaded to artifact to be written by post PR workflow run
      - name: Coverage comment
        id: coverage_comment
        uses: py-cov-action/python-coverage-comment-action@57fcc5cd0dc3e5e78df0d7acd857dd1eed0378c1 # v3
        with:
          GITHUB_TOKEN: ${{ github.token }}
        if: ${{ github.event_name == 'pull_request' }}

      - name: Store Pull Request comment to be posted
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        if: |
          ${{ github.event_name == 'pull_request' &&
          steps.coverage_comment.outputs.COMMENT_FILE_WRITTEN == 'true' }}
        with:
          name: python-coverage-comment-action
          path: python-coverage-comment-action.txt
