name: (sub) Unit Tests

defaults:
  run:
    shell: bash

on:
  workflow_call:
    inputs:
      python_version:
        description: A version of Python to install
        type: string
        required: true

jobs:

  unittests:
    name: Verify unit tests are successful
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python_version }}

      - name: Install Poetry
        uses: Gr1N/setup-poetry@v8

      - name: Create Poetry venv
        run: |
          poetry env use ${{ inputs.python_version }}
          poetry install

      - name: Run unit tests and coverage
        run: poetry run make test_coverage

      # coverage results are uploaded to artifact to be inspected by post PR workflow run
      - name: Save coverage results
        uses: actions/upload-artifact@v4
        with:
          name: pr-coverage
          path: coverage.xml
        if: ${{ github.event_name == 'pull_request' }}
