name: (sub) Documentation check

defaults:
  run:
    shell: bash

on:
  workflow_call:
    inputs:
      python_version:
        description: A version of Python to install
        type: string
        required: true

env:
  PYTHON_VERSION: "3.8.16"      # TODO fixed python version until we find a replacement for pydoc-markdown
  # PYTHON_VERSION: ${{ inputs.python_version }}

jobs:

  documentation:
    name: Verify if generated API documentation is up to date
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install Python
        uses: actions/setup-python@b64ffcaf5b410884ad320a9cfac8866006a109aa # v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # - name: Install Poetry
      #   uses: Gr1N/setup-poetry@15821dc8a61bc630db542ae4baf6a7c19a994844 # v8
      #   with:
      #     poetry-version: "1.8.5"

      # - name: Create Poetry venv
      #   run: | 
      #     poetry env use $PYTHON_VERSION
      #     poetry install

      # - name: Generate API docs
      #   run: poetry run make documentation

      - name: Install documentation dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools
          pip install -r requirements-docs.txt

      - name: Generate API docs
        run: make documentation

      - name: Check if documentation needs updating
        run: |
          if [ "$(git status --porcelain)" ]; then 
            git status
            echo "Documentation changes detected. Please update the documentation and commit the changes."
            exit 1
          else
            echo "No documentation changes detected."
            exit 0
          fi
