name: (sub) Code Format and Security

defaults:
  run:
    shell: bash

on:
  workflow_call:

jobs:
  fetch:
    name: Fetch the updated documentation
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: pack the documentation
        working-directory: docs
        run: tar --exclude .DS_Store --exclude sidebars.js -cvf documentation.tar *
      - name: upload the documentation artifact
        uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: docs/documentation.tar

  update:
    name: Prepare a PR for pan.dev
    needs: [fetch]
    runs-on: ubuntu-latest
    steps:
      - name: checkout pan.dev fork
        uses: actions/checkout@v3
        with:
          repository: PaloAltoNetworks/panos-upgrade-assurance-pan.dev
      - name: download documentation artifact
        uses: actions/download-artifact@v3
        with:
          name: documentation
          path: products/panos/docs
      - name: unpack the documentation
        working-directory: products/panos/docs
        run: |
          rm -rf 'panos-upgrade-assurance'
          tar xvf documentation.tar
          rm -f documentation.tar
          ls -ltr
          ls -ltr 'panos-upgrade-assurance'
