name: (sub) Documentation check

defaults:
  run:
    shell: bash

on:
  workflow_call:
    inputs:
      python_version:
        description: A version of Python to install
        type: string
        required: true

jobs:

  documentation:
    name: Verify if generated API documentation is up to date
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install Python
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4
        with:
          python-version: ${{ inputs.python_version }}

      - name: Install Poetry
        uses: Gr1N/setup-poetry@15821dc8a61bc630db542ae4baf6a7c19a994844 # v8

      - name: Create Poetry venv
        run: | 
          poetry env use ${{ inputs.python_version }}
          poetry install

      - name: Generate API docs
        run: poetry run make documentation

      - name: Check if documentation needs updating
        run: |
          if [ "$(git status --porcelain)" ]; then 
            git status
            exit 1
          else
            exit 0
          fi
