name: (sub) Code Format and Security

defaults:
  run:
    shell: bash

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      head_branch:
        description: Name of a branch from which the PR in source repository is created
        type: string
        required: true
      preview:
        description: Flag that indicates if the PR in PAN.DEV should be a preview PR or a release PR
        type: boolean
        required: true

jobs:
  fetch:
    name: Fetch the updated documentation
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: pack the documentation
        working-directory: docs
        run: tar --exclude .DS_Store --exclude sidebars.js -cvf documentation.tar *
      - name: upload the documentation artifact
        uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: docs/documentation.tar

  update:
    name: Prepare a PR for pan.dev
    needs: [fetch]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: checkout pan.dev fork
        uses: actions/checkout@v3
        with:
          repository: PaloAltoNetworks/pan.dev
          token: ${{ secrets.CLSC_PAT }}

      - name: download documentation artifact
        uses: actions/download-artifact@v3
        with:
          name: documentation
          path: products/panos/docs

      - name: unpack the documentation
        working-directory: products/panos/docs
        run: |
          rm -rf 'panos-upgrade-assurance'
          tar xvf documentation.tar
          rm -f documentation.tar

      - name: prepare title and body strings
        id: pr_data
        env:
          PREVIEW: ${{ inputs.preview }}
          BRANCH: ${{ inputs.head_branch }}
        run: |
          if [ "$PREVIEW" == "true" ]; then
            echo "pr_title=[PAN-OS Upgrade Assurance][${BRANCH}] documentation PREVIEW - do NOT MERGE" >> $GITHUB_OUTPUT
            echo "pr_body=DO NOT MERGE - preview PR made for changes on branch: ${$BRANCH}." >> $GITHUB_OUTPUT
          else
            echo "pr_title=[PAN-OS Upgrade Assurance] documentation update for release: ${BRANCH}" >> $GITHUB_OUTPUT
            echo "pr_body=A PR made for changes introduced into documentation on ${BRANCH} release." >> $GITHUB_OUTPUT
          fi

      - name: create a PR to upstream pan.dev
        id: pr
        uses: peter-evans/create-pull-request@v5
        with:
          push-to-fork: PaloAltoNetworks/panos-upgrade-assurance-pan.dev
          token: ${{ secrets.CLSC_PAT }}
          delete-branch: true
          branch: "${{ inputs.head_branch }}"
          title: ${{ steps.pr_data.outputs.pr_title }} 
          commit-message: "docs: PanOS Upgrade Assurance documentation update"
          body: |
            # Description
            
            ${{ steps.pr_data.outputs.pr_body }}

            # Types of changes

            New feature (non-breaking change which adds functionality)

      - name: comment back on the original PR
        if: steps.pr.outputs.pull-request-url != '' && github.event.action == 'opened' && inputs.preview == 'true'
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          repository: ${{ github.repository }}
          body: |
            A Preview PR in PanDev repo has been created. You can view it [here](${{ steps.pr.outputs.pull-request-url }}).
