name: (sub) Code Format and Security

defaults:
  run:
    shell: bash

on:
  workflow_call:
    inputs:
      python_version:
        description: A version of Python to install
        type: string
        required: true

jobs:
  format:
    name: Verify code formatting and security
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install Python
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4
        with:
          python-version: ${{ inputs.python_version }}

      - name: Install Poetry
        uses: Gr1N/setup-poetry@15821dc8a61bc630db542ae4baf6a7c19a994844 # v8
        with:
          poetry-version: "1.8.5"

      - name: Create Poetry venv
        run: |
          poetry env use ${{ inputs.python_version }}
          poetry install

      - name: Run flake
        run: poetry run make lint

      - name: Run black
        run: poetry run make format_check

      - name: Run bandit
        run: poetry run make security
