name: (sub) Code Format and Security

defaults:
  run:
    shell: bash

permissions:
  contents: read

on:
  workflow_call:

jobs:
  fetch:
    name: Fetch the updated documentation
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: pack the documentation
        working-directory: docs
        run: tar --exclude .DS_Store --exclude sidebars.js -cvf documentation.tar *
      - name: upload the documentation artifact
        uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: docs/documentation.tar

  update:
    name: Prepare a PR for pan.dev
    needs: [fetch]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: checkout pan.dev fork
        uses: actions/checkout@v3
        with:
          repository: PaloAltoNetworks/pan.dev
          token: ${{ secrets.CLSC_PAT }}
      - name: download documentation artifact
        uses: actions/download-artifact@v3
        with:
          name: documentation
          path: products/panos/docs
      - name: unpack the documentation
        working-directory: products/panos/docs
        run: |
          rm -rf 'panos-upgrade-assurance'
          tar xvf documentation.tar
          rm -f documentation.tar
      - name: create a PR to upstram pan.dev
        uses: peter-evans/create-pull-request@v5
        with:
          push-to-fork: PaloAltoNetworks/panos-upgrade-assurance-pan.dev
          token: ${{ secrets.CLSC_PAT }}
          # delete-branch: true
          # branch: PaloAltoNetworks/panos-upgrade-assurance-pan.dev:upgrade-assurance-documentation-update
          # title: "[PAN-OS Upgrade Assurance] documentation PREVIEW - do NOT MERGE"
          # commit-message: "docs: documentation update"
          # body: |
          #   # Description
            
          #   DO NOT MERGE - preview PR

          #   # Types of changes

          #   New feature (non-breaking change which adds functionality)
